stages:
  - stage: Stage1
    jobs:
      - job: UpdateChangeRequest
        steps:
          - task: UpdateServiceNowChangeRequest@2
            inputs:
               ServiceNowConnection: 'myservice'
               ChangeRequestNumber: 'CHG0030881'
               NewStatus: '3'
               CloseCode: 'successful'
               CloseNotes: 'cr approved'
pool: server